const key='little-lingo-state-v2';let saved={completed:[]};try{saved=JSON.parse(localStorage.getItem(key))||saved}catch{}let completed=new Set(saved.completed||[]),progress=1+completed.size+(completed.size===3?1:0),raf=0,playing=false,totalRounds=3,audioCtx=null,musicTimer=0,musicTheme=0,pending=[];
const $=s=>document.querySelector(s),stops=[...document.querySelectorAll('.stop')],path=$('#trail-progress'),traveler=$('#traveler'),modal=$('#modal'),positions=[['5%','14%'],['27%','3%'],['50%','18%'],['74%','0%'],['96%','18%']];
const later=(fn,ms)=>{const id=setTimeout(fn,ms);pending.push(id);return id};function clearPending(){pending.forEach(clearTimeout);pending=[]}
function render(){progress=1+completed.size+(completed.size===3?1:0);stops.forEach((s,i)=>s.classList.toggle('done',i<progress));$('#star-count').textContent=progress;const l=path.getTotalLength();path.style.strokeDasharray=`${l}`;path.style.strokeDashoffset=`${l*(1-(progress-1)/4)}`;traveler.style.left=positions[progress-1][0];traveler.style.top=positions[progress-1][1]}
function soundOn(){return!$('#sound').classList.contains('off')}function audio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(f,d=.12,type='sine',v=.06,delay=0){if(!soundOn())return;const a=audio(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.001,a.currentTime+delay);g.gain.exponentialRampToValueAtTime(v,a.currentTime+delay+.01);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+delay+d);o.connect(g).connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+d+.02)}
function sfx(k){if(k==='good'){tone(523,.12,'sine',.09);tone(659,.12,'sine',.09,.1);tone(784,.18,'sine',.09,.2)}if(k==='bad'){tone(210,.15,'sawtooth',.05);tone(155,.2,'sawtooth',.04,.12)}if(k==='jump'){tone(260,.1,'triangle',.07);tone(540,.14,'triangle',.06,.08)}if(k==='pop'){tone(760,.07,'sine',.08);tone(1030,.09,'sine',.05,.04)}}
function victoryMusic(){[392,523,659,784,1047].forEach((n,i)=>tone(n,.38,'triangle',.11,i*.16));later(()=>[523,659,784,1047].forEach((n,i)=>tone(n,.55,'sine',.08,i*.08)),900)}
function startMusic(theme=0){musicTheme=theme;stopMusic();if(!soundOn())return;const songs=[[262,330,392,330],[294,392,440,392],[330,392,494,392]],notes=songs[theme];let n=0;musicTimer=setInterval(()=>tone(notes[n++%4],.44,'sine',.016),650)}function stopMusic(){clearInterval(musicTimer);musicTimer=0}
function say(t){if(!('speechSynthesis'in window)||!soundOn())return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.7;u.pitch=1.12;speechSynthesis.speak(u)}
function image(src){const i=new Image();i.src=src;return i}function chromaSprite(src){const out=document.createElement('canvas');out.width=1254;out.height=1254;const img=new Image();img.onload=()=>{const c=out.getContext('2d');c.drawImage(img,0,0,out.width,out.height);const d=c.getImageData(0,0,out.width,out.height);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(g>130&&g>r*1.35&&g>b*1.25)d.data[i+3]=0}c.putImageData(d,0,0)};img.src=src;return out}function bg(c,img,color){c.fillStyle=color;c.fillRect(0,0,700,380);if(img.complete)c.drawImage(img,0,0,700,380)}function rounded(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}function shuffled(a){return[...a].sort(()=>Math.random()-.5)}
function cleanup(){playing=false;cancelAnimationFrame(raf);clearPending();stopMusic();if('speechSynthesis'in window)speechSynthesis.cancel()}
function setup(title,label,mission,hint,controls,total=3,music=0){cleanup();playing=true;totalRounds=total;modal.hidden=false;$('#game-title').textContent=title;$('#game-label').textContent=label;$('#feedback').textContent='';$('#game-content').innerHTML=`<div class="hud"><span class="mission">${mission}</span><span class="hearts">♥ ♥ ♥</span><span class="round">1 / ${total}</span></div><div class="game-stage"><canvas width="700" height="380"></canvas><div class="game-message">Приготовься!</div></div><div class="game-controls">${controls}<button class="hint-btn">💡 Подсказка</button></div>`;$('.hint-btn').onclick=()=>{let p=$('.hint-pop');if(p){p.remove();return}p=document.createElement('div');p.className='hint-pop';p.textContent=hint;$('.game-stage').append(p);later(()=>p?.remove(),4200)};later(()=>$('.game-message')?.remove(),950);startMusic(music);return $('canvas')}
function hud(n,mission,total=totalRounds){$('.round').textContent=`${n} / ${total}`;$('.mission').textContent=mission}function lives(n){$('.hearts').textContent='♥ '.repeat(n)||'♡'}
function message(text,type='good',time=950){let m=$('.game-message');if(!m){m=document.createElement('div');$('.game-stage').append(m)}m.className=`game-message ${type}`;m.textContent=text;clearTimeout(message.timer);message.timer=later(()=>m?.remove(),time)}
function endScreen(html){playing=false;cancelAnimationFrame(raf);stopMusic();$('.game-stage').insertAdjacentHTML('beforeend',html)}
function unlockChest(){victoryMusic();const party=document.createElement('div');party.className='chest-party';party.innerHTML=`<div class="chest-party-card"><div class="confetti"></div><img src="assets/magic-chest.png" alt="Открытый волшебный сундук"><h2>Сундук открыт!</h2><p>Все миры исследованы. Ты — настоящий Little Lingo Explorer!</p><button>Продолжить приключение</button></div>`;document.body.append(party);party.querySelector('button').onclick=()=>party.remove();say('The magic chest is open! Congratulations!')}
function finish(title,replay,gameId){const fresh=!completed.has(gameId);sfx('good');endScreen(`<div class="game-result"><div class="confetti"></div><div class="result-card" style="position:relative;z-index:2"><span style="font-size:66px">⭐</span><b>${title}</b><p>${fresh?'Ура! Звезда заработана!':'Ура! Приключение пройдено снова!'}</p><div class="result-actions"><button class="again">↻ Играть ещё раз</button><button class="reward">${fresh?'Забрать звезду':'На карту'}</button></div></div></div>`);$('.again').onclick=()=>{closeGame();later(replay,50)};$('.reward').onclick=()=>{const before=completed.size;completed.add(gameId);localStorage.setItem(key,JSON.stringify({completed:[...completed]}));render();closeGame();if(before<3&&completed.size===3)later(unlockChest,250)};say(fresh?'Wonderful! You earned a star!':'Wonderful!')}
function gameOver(title,replay){sfx('bad');endScreen(`<div class="game-result"><div class="result-card"><span style="font-size:60px">💛</span><b>${title}</b><p>Сердечки закончились. Попробуем ещё раз?</p><div class="result-actions"><button class="exit-game">Выйти</button><button class="reward retry">↻ Играть снова</button></div></div></div>`);$('.exit-game').onclick=closeGame;$('.retry').onclick=()=>{closeGame();later(replay,50)}}
function closeGame(){cleanup();modal.hidden=true}

function wordSafari(){
 const targets=[['CAT','кот'],['DOG','собака'],['SUN','солнце'],['BIRD','птица'],['APPLE','яблоко'],['STAR','звезда']],decoys=['FISH','TREE','MOON','BALL','HAT','BOOK'];const cvs=setup('Word Safari','САФАРИ СЛОВ','Поймай CAT','Передвигай корзину. Лови только слово из задания — все карточки выглядят одинаково.','<button class="left">← Влево</button><button class="right">Вправо →</button>',6,0),c=cvs.getContext('2d'),scene=image('assets/game-word-bg.png');
 let basket=310,keys={},cards=[],round=0,hp=3,last=performance.now(),spawn=.15,count=0,pause=false,flash='';say(targets[0][0]);const move=e=>{const r=cvs.getBoundingClientRect();basket=Math.max(0,Math.min(610,(e.clientX-r.left)*700/r.width-45))};cvs.onpointermove=move;const kd=e=>keys[e.key]=true,ku=e=>keys[e.key]=false;addEventListener('keydown',kd);addEventListener('keyup',ku);const hold=(q,k)=>{const b=$(q);b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointerleave=()=>keys[k]=false};hold('.left','ArrowLeft');hold('.right','ArrowRight');const oldClose=closeGame;
 function add(){count++;const word=count%4===0?targets[round][0]:shuffled([...decoys,targets[round][0]])[0];cards.push({x:20+Math.random()*580,y:-55,v:92+Math.random()*34,word})}function next(){if(!playing)return;round++;cards=[];pause=false;if(round===6){removeEventListener('keydown',kd);removeEventListener('keyup',ku);finish('Словарное сафари пройдено!',wordSafari,'words');return}hud(round+1,`Поймай ${targets[round][0]}`);say(targets[round][0]);spawn=.35}
 function lose(word){flash='bad';sfx('bad');hp--;lives(hp);message(`Это ${word}. Ищи ${targets[round][0]}`,'bad');later(()=>flash='',500);if(hp===0){removeEventListener('keydown',kd);removeEventListener('keyup',ku);gameOver('Корзинка опустела',wordSafari)}}
 function loop(now){if(!playing)return;const dt=Math.min(.03,(now-last)/1000);last=now;if(keys.ArrowLeft)basket-=310*dt;if(keys.ArrowRight)basket+=310*dt;basket=Math.max(0,Math.min(610,basket));if(!pause&&(spawn-=dt)<=0){add();spawn=.68}cards.forEach(o=>o.y+=o.v*dt);for(let i=cards.length-1;i>=0;i--){const o=cards[i];if(o.y>282&&o.y<355&&o.x+100>basket&&o.x<basket+95){cards.splice(i,1);if(o.word===targets[round][0]){pause=true;flash='good';sfx('good');message(`Верно! ${o.word} — ${targets[round][1]}`);say(o.word);later(next,850)}else lose(o.word)}else if(o.y>410)cards.splice(i,1)}bg(c,scene,'#aee1e7');c.font='900 18px Nunito';c.textAlign='center';cards.forEach(o=>{c.fillStyle='#fffaf0';rounded(c,o.x,o.y,100,46,13);c.strokeStyle='#e7b871';c.lineWidth=3;c.stroke();c.fillStyle='#29383d';c.fillText(o.word,o.x+50,o.y+29)});if(flash){c.save();c.shadowBlur=30;c.shadowColor=flash==='good'?'#35e66a':'#ff3030';c.fillStyle=flash==='good'?'#85e99a':'#ff8b7e';c.beginPath();c.ellipse(basket+47,334,62,26,0,0,7);c.fill();c.restore()}c.font='62px serif';c.fillText('🧺',basket+46,354);raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)
}

function balloonJump(){
 const cats=[{name:'Animals',voice:'Collect animals',words:['CAT','DOG','BIRD']},{name:'Toys',voice:'Collect toys',words:['BALL','DOLL','KITE']},{name:'Clothes',voice:'Collect clothes',words:['HAT','SHOE','SOCK']}],all=['CAT','DOG','BIRD','BALL','DOLL','KITE','HAT','SHOE','SOCK','SUN','APPLE','BOOK','TREE'];const cvs=setup('Balloon Jump','ПРЫЖКИ ЗА СЛОВАМИ','Animals · 0 из 3','Прыгай за словами нужной категории. В каждой попытке ровно 10 шаров. Пробел тоже запускает прыжок.','<button class="action jump">↑ JUMP · ПРЫЖОК</button>',3,1),c=cvs.getContext('2d'),scene=image('assets/game-sky-bg.png'),bunnyRun=chromaSprite('assets/bunny-run-source.png'),bunnyJump=chromaSprite('assets/bunny-jump-source.png');
 let round=0,collected=new Set(),queue=[],shown=0,balloon=null,bunnyY=286,vy=0,hp=3,last=performance.now(),spoken=false,waiting=false;
 function newAttempt(){collected=new Set();shown=0;const right=cats[round].words,wrong=shuffled(all.filter(x=>!right.includes(x))).slice(0,7);queue=shuffled([...right,...wrong]);hud(round+1,`${cats[round].name} · 0 из 3`);say(cats[round].voice);nextBalloon()}
 function nextBalloon(){if(!playing||waiting)return;if(shown===10){attemptEnd();return}const word=queue[shown++];balloon={word,x:760,y:178,color:['#ff8d7c','#ffd45e','#80d5dc','#b996d3'][shown%4]};spoken=false}
 function jump(){if(bunnyY>=285){vy=-465;sfx('jump')}}$('.jump').onclick=jump;const kd=e=>{if(e.code==='Space'||e.key==='ArrowUp'){e.preventDefault();jump()}};addEventListener('keydown',kd);
 function lose(text){hp--;lives(hp);sfx('bad');message(text,'bad');if(hp===0){removeEventListener('keydown',kd);gameOver('Шарики улетели',balloonJump);return true}return false}
 function resolve(caught){const word=balloon.word,isRight=cats[round].words.includes(word);balloon=null;if(caught){if(isRight){if(!collected.has(word)){collected.add(word);sfx('good');say(word);message(`${word} пойман!`)}else message(`${word} уже есть`,'bad')}else if(lose(`${word} не относится к ${cats[round].name}`))return}else if(isRight&&lose(`Упущено нужное слово ${word}`))return;hud(round+1,`${cats[round].name} · ${collected.size} из 3`);later(nextBalloon,360)}
 function attemptEnd(){waiting=true;if(collected.size===3){round++;if(round===3){removeEventListener('keydown',kd);finish('Три коллекции собраны!',balloonJump,'moves');return}waiting=false;message(`${cats[round-1].name} собрано!`);later(newAttempt,800)}else{endScreen(`<div class="game-result"><div class="result-card"><span style="font-size:55px">🎈</span><b>10 шаров пролетели</b><p>Собрано ${collected.size} из 3. Повторим ${cats[round].name}?</p><div class="result-actions"><button class="exit-game">Выйти</button><button class="reward retry-round">Повторить раунд</button></div></div></div>`);$('.exit-game').onclick=closeGame;$('.retry-round').onclick=()=>{$('.game-result').remove();playing=true;waiting=false;newAttempt();startMusic(1);last=performance.now();raf=requestAnimationFrame(loop)}}}
 newAttempt();function loop(now){if(!playing)return;const dt=Math.min(.03,(now-last)/1000);last=now;vy+=940*dt;bunnyY+=vy*dt;if(bunnyY>286){bunnyY=286;vy=0}if(balloon){balloon.x-=105*dt;if(balloon.x<610&&!spoken){spoken=true;say(balloon.word)}if(Math.abs(balloon.x-145)<54&&bunnyY<235)resolve(true);else if(balloon&&balloon.x<-80)resolve(false)}bg(c,scene,'#8ddcf0');c.fillStyle='#fffaf0dd';rounded(c,18,16,300,48,15);c.fillStyle='#2b3d45';c.font='900 15px Nunito';c.textAlign='left';c.fillText(`${cats[round]?.name||''}: ${[...collected].join(', ')||'—'} · шар ${Math.min(shown,10)}/10`,32,46);const sprite=bunnyY<280?bunnyJump:bunnyRun;if(sprite.width)c.drawImage(sprite,72,bunnyY-62,142,142);if(balloon){c.strokeStyle='#755a4b';c.lineWidth=2;c.beginPath();c.moveTo(balloon.x,223);c.lineTo(balloon.x,285);c.stroke();c.fillStyle=balloon.color;c.beginPath();c.ellipse(balloon.x,178,72,55,0,0,7);c.fill();c.fillStyle='#26383f';c.font='900 18px Nunito';c.textAlign='center';c.fillText(balloon.word,balloon.x,184)}raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)
}

function soundGarden(){
 const rounds=[{target:'FLOWER',pool:['FLOWER','APPLE','FISH','TREE','MOON','CAT','BOOK']},{target:'CAT',pool:['SUN','CAT','TREE','DOG','BALL','BIRD','HAT']},{target:'BIRD',pool:['DOG','MOON','BIRD','FISH','KITE','SHOE','SUN']},{target:'APPLE',pool:['APPLE','BALL','CAT','BOOK','HAT','TREE','DOG']},{target:'KITE',pool:['DOLL','KITE','SOCK','BIRD','MOON','BALL','FISH']},{target:'SHOE',pool:['HAT','DOG','SHOE','SUN','BOOK','CAT','APPLE']}];const cvs=setup('Sound Garden','САД ЗВУКОВ','Послушай слово','Нажми «Слушать», затем выбери цветок с услышанным английским словом.','<button class="action replay">♪ СЛУШАТЬ</button>',6,2),c=cvs.getContext('2d'),scene=image('assets/game-sound-bg.png');let round=0,flowers=[],last=performance.now(),locked=false,hp=3;
 function make(){if(!playing)return;locked=false;const spots=shuffled([{x:90,y:125},{x:225,y:110},{x:360,y:135},{x:510,y:105},{x:620,y:175},{x:175,y:260},{x:440,y:255}]),order=shuffled(rounds[round].pool);flowers=order.map((word,i)=>({word,x:spots[i].x,y:spots[i].y,vx:(Math.random()>.5?1:-1)*(12+Math.random()*10),vy:(Math.random()>.5?1:-1)*(9+Math.random()*8),color:['#ff927c','#ffd45e','#aa8ccc','#6dccbd','#f5a5cc','#86bfe0','#f3a56b'][i]}));hud(round+1,'Какое слово звучит?');later(()=>say(rounds[round].target),300)}make();$('.replay').onclick=()=>say(rounds[round].target);
 cvs.onclick=e=>{if(locked||!playing)return;const r=cvs.getBoundingClientRect(),x=(e.clientX-r.left)*700/r.width,y=(e.clientY-r.top)*380/r.height,f=flowers.find(q=>Math.hypot(q.x-x,q.y-y)<48);if(!f)return;if(f.word===rounds[round].target){locked=true;sfx('pop');later(()=>sfx('good'),100);message(`Верно! ${f.word} расцвёл!`);say(f.word);round++;if(round===6)later(()=>finish('Весь сад расцвёл!',soundGarden,'sounds'),700);else later(make,750)}else{hp--;lives(hp);sfx('bad');message(`Это ${f.word}. Послушай снова`,'bad');if(hp===0){locked=true;gameOver('Сад уснул',soundGarden)}else{say(rounds[round].target);f.vx*=-2;f.vy*=-2}}};
 function loop(now){if(!playing)return;const dt=Math.min(.03,(now-last)/1000);last=now;flowers.forEach(f=>{f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.x<62||f.x>638)f.vx*=-1;if(f.y<85||f.y>285)f.vy*=-1});bg(c,scene,'#a78fc8');flowers.forEach(f=>{c.strokeStyle='#4c9563';c.lineWidth=5;c.beginPath();c.moveTo(f.x,f.y+30);c.lineTo(f.x,f.y+68);c.stroke();c.fillStyle=f.color;for(let a=0;a<6;a++){c.beginPath();c.ellipse(f.x+Math.cos(a)*25,f.y+Math.sin(a)*25,18,12,a,0,7);c.fill()}c.fillStyle='#ffe27a';c.beginPath();c.arc(f.x,f.y,21,0,7);c.fill();c.fillStyle='#303b42';c.font='900 11px Nunito';c.textAlign='center';c.fillText(f.word,f.x,f.y+4)});raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop)
}
const games={words:wordSafari,moves:balloonJump,sounds:soundGarden};document.querySelectorAll('.game-card').forEach(card=>{const launch=()=>games[card.dataset.game]();card.onclick=launch;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();launch()}}});$('.close').onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};$('#reset').onclick=()=>{if(confirm('Обнулить все собранные звёзды?')){completed.clear();localStorage.setItem(key,JSON.stringify({completed:[]}));render()}};$('#sound').onclick=e=>{e.stopPropagation();e.currentTarget.classList.toggle('off');e.currentTarget.textContent=e.currentTarget.classList.contains('off')?'×':'♪';if(!soundOn()){stopMusic();if('speechSynthesis'in window)speechSynthesis.cancel()}else if(playing)startMusic(musicTheme)};render();
